---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    app: spinnaker
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  namespace: spinnaker
  labels:
    app: spinnaker
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: spinnaker
  labels:
    app: spinnaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinnaker
  template:
    metadata:
      labels:
        app: spinnaker
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio
        volumeMounts:
        - name: minio-storage
          mountPath: /data
          env:
          - name: MINIO_ROOT_USER
            value: "minioadmin"
          - name: MINIO_ROOT_PASSWORD
            value: "minioadmin"
          command:
          - "/bin/sh"
          - "-c"
          - "minio server /data --address :9000 --console-address :9001"
        volumes:
        - name: minio-storage
          persistentVolumeClaim:
	    claimName: minio-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: minio-api
  namespace: spinnaker
  labels:
    app: spinnaker
spec:
  selector:
    app: spinnaker
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: spinnaker
  labels:
    app: spinnaker
spec:
  selector:
    app: spinnaker
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9101
      targetPort: 9001
